/*jslint  browser:  true,
            newcap:   true,
            nomen:    false,
            plusplus: false,
            undef:    true,
            vars:     false,
            indent:   2,
            sloppy:   true,
            white:    false */

var Services = require ('./services.js');

// Device profiles, from more to less specific
// If a device satisfies all the conditions, the device is 'identified' and the attendant device data is stored

var DeviceProfiles = [
  {services: [Services.apple_mobdev], mac_ranges: ["60:fa:cd"],
    device: {model: 'iPhone 4S', type: 'phone'}},
  {services: [Services.apple_mobdev], mac_ranges: ["7c:c5:37"],
    device: {model: 'iPhone 4', type: 'phone'}},
  {services: [Services.apple_mobdev], mac_ranges: ["58:55:ca", "64:b9:e8", "f8:1e:df"],
    device: {model: 'iPhone', type: 'phone'}},
  {services: [Services.apple_mobdev], mac_ranges: ["a4:d1:d2"],
    device: {model: 'iPad 2', type: 'tablet'}},
  {services: [Services.apple_mobdev],
    device: {model: 'iOS Device', type: 'phone'}},
  {services: [Services.ipp], mac_ranges: ["b4:99:ba"],
    device: {model: 'HP Photosmart', type: 'printer'}},
  {services: [Services.ipp],
    device: {type: 'printer'}},
  {services: [Services.snmp], mac_ranges: ["0:14:bf"],
    device : {model: "Linksys WRT54G", type: 'networking'}},
  {services: [Services.snmp], mac_ranges: ["94:fe:f4"],
    device : {model: "BT Home Hub 3", type: 'networking'}},
  {services: [Services.snmp],
    device : {type: 'networking'}},
  {services: [Services.airport], //mac_ranges: ["f0:b4:79"],
    device : {model: "Airport Express", type: 'networking'}},
  {services: [Services.heatmiser],
    device : {model: "Heatmiser PRT-TS Wifi RF", type: 'misc'}},
  {mac_ranges: ["0:1c:c3"],
    device : {model: "Pace Sky HD+", type: 'set_top_box'}},
  {mac_ranges: ["0:25:0"],
    device : {model: "Mac Mini (Early 2009)", type: 'computer'}},
  {mac_ranges: ["0:90:a9"],
    device : {model: "WD MyBook World", type: 'computer'}},
  {mac_ranges: ["18:87:96"],
    device : {model: "HTC one", type: 'phone'}},
  {mac_ranges: ["38:e7:d8"],
    device : {model: "HTC desire", type: 'phone'}},
  {mac_ranges: ["58:b0:35", "68:a8:6d", "10:40:f3", "f8:1e:df", "0:26:bb", "0:25:0", "b8:f6:b1", "f0:b4:79", "0:1f:5b", "b8:8d:12", "e0:f8:47", "4:c:ce", "20:c9:d0", "0:26:08", "c8:2a:14", "3c:7:54", "c8:bc:c8", "e4:ce:8f", ],
    device : {model: 'Macbook Pro 15" (Mid 2010)', type: 'laptop'}},
  {mac_ranges: ["7c:d1:c3", "b8:8d:12", "10:40:f3", "70:56:81", "44:2a:60", "28:37:37", "60:c5:47", "b8:8d:12", "4:c:ce"],
    device : {model: 'Macbook Air 13"', type: 'laptop'}},
  {mac_ranges: ["7c:ed:8d"],
    device : {model: "XBox 360", type: 'console'}},
  {mac_ranges: ["b8:27:eb"],
    device : {model: "Raspberry Pi", type: 'computer'}},
  {mac_ranges: ["d8:b3:77"],
    device : {model: "HTC sensation", type: 'phone'}},
  {mac_ranges: ["dc:d3:21"],
    device : {model: "Humax DTR-T1000", type: 'set_top_box'}},
]

module.exports = DeviceProfiles;
