/*jslint  browser:  true,
            newcap:   true,
            nomen:    false,
            plusplus: false,
            undef:    true,
            vars:     false,
            indent:   2,
            sloppy:   true,
            white:    false */

var Services = require ('./services.js');

// Device profiles, from more to less specific
// If a device satisfies all the conditions, the device is 'identified' and the attendant device data is stored

var DeviceProfiles = [
  {services: [Services.apple_mobdev], mac_ranges: ["60:fa:cd"],
    device: {model: 'iPhone 4S', type: 'phone'}},
  {services: [Services.apple_mobdev], mac_ranges: ["58:55:ca", "64:b9:e8", "7c:c5:37", "f8:1e:df"],
    device: {model: 'iPhone', type: 'phone'}},
  {services: [Services.apple_mobdev], mac_ranges: ["a4:d1:d2"],
    device: {model: 'iPad', type: 'tablet'}},
  {services: [Services.apple_mobdev],
    device: {model: 'iOS Device', type: 'phone'}},
  {services: [Services.ipp], mac_ranges: ["b4:99:ba"],
    device: {model: 'HP Photosmart', type: 'printer'}},
  {services: [Services.ipp],
    device: {type: 'printer'}},
  {services: [Services.snmp], mac_ranges: ["0:14:bf"],
    device : {model: "Linksys WRT54G", type: 'networking'}},
  {mac_ranges: ["0:1c:c3"],
    device : {model: "Pace Sky HD+", type: 'set_top_box'}},
  {services: [Services.heatmiser],
    device : {model: "Heatmiser PRT-TS Wifi RF", type: 'misc'}},
  {mac_ranges: ["0:25:0"],
    device : {model: "Mac Mini", type: 'computer'}},
  {mac_ranges: ["0:90:a9"],
    device : {model: "WD MyBook World", type: 'computer'}},
  {mac_ranges: ["18:87:96"],
    device : {model: "HTC one", type: 'phone'}},
  {mac_ranges: ["38:e7:d8"],
    device : {model: "HTC desire", type: 'phone'}},
  {mac_ranges: ["58:b0:35", "68:a8:6d", "f8:1e:df"],
    device : {model: "Macbook Pro", type: 'laptop'}},
  {mac_ranges: ["7c:d1:c3", "b8:8d:12"],
    device : {model: "Macbook Air", type: 'laptop'}},
  {mac_ranges: ["7c:ed:8d"],
    device : {model: "XBox 360", type: 'console'}},
  {services: [Services.snmp], mac_ranges: ["94:fe:f4"],
    device : {model: "BT Home Hub 3", type: 'networking'}},
  {mac_ranges: ["b8:27:eb"],
    device : {model: "Raspberry Pi", type: 'computer'}},
  {mac_ranges: ["d8:b3:77"],
    device : {model: "HTC sensation", type: 'phone'}},
  {mac_ranges: ["dc:d3:21"],
    device : {model: "Humax DTR-T1000", type: 'set_top_box'}},
  {services: [Services.airport], //mac_ranges: ["f0:b4:79"],
    device : {model: "Airport Express", type: 'networking'}},
  {services: [Services.snmp],
    device : {type: 'networking'}},
]

module.exports = DeviceProfiles;
